export const routes = {
  home: "/",
  layanan: "/layanan",
  jasa: "/jasa",
  kitchenSet: "/layanan/kitchen-set",
  customFurniture: "/layanan/custom-furniture",
  interiorRumah: "/layanan/interior-rumah",
  interiorToko: "/layanan/interior-toko",
  backdropTv: "/layanan/backdrop-tv",
  lemariCustom: "/layanan/lemari-custom",
  boothUsaha: "/layanan/booth-usaha",
  akrilikCustom: "/layanan/akrilik-custom",
  aluminium: "/layanan/aluminium",
  kanopi: "/layanan/kanopi",
  gallery: "/gallery",
  kontak: "/kontak",
  estimasiBiaya: "/estimasi-biaya",
  tentangKami: "/tentang-kami",
  artikel: "/artikel",
};

export const sitemapRoutes = [
  { path: routes.home, priority: 1.0 },
  { path: routes.layanan, priority: 0.9 },
  { path: routes.jasa, priority: 0.86 },
  { path: "/jasa/kitchen-set-purwokerto", priority: 0.86 },
  { path: "/jasa/booth-usaha-purwokerto", priority: 0.84 },
  { path: "/jasa/akrilik-custom-purwokerto", priority: 0.82 },
  { path: "/jasa/aluminium-purwokerto", priority: 0.82 },
  { path: "/jasa/kanopi-purwokerto", priority: 0.8 },
  { path: routes.kitchenSet, priority: 0.9 },
  { path: routes.customFurniture, priority: 0.88 },
  { path: routes.interiorRumah, priority: 0.86 },
  { path: routes.interiorToko, priority: 0.86 },
  { path: routes.backdropTv, priority: 0.76 },
  { path: routes.lemariCustom, priority: 0.76 },
  { path: routes.boothUsaha, priority: 0.74 },
  { path: routes.akrilikCustom, priority: 0.74 },
  { path: routes.aluminium, priority: 0.74 },
  { path: routes.kanopi, priority: 0.74 },
  { path: routes.gallery, priority: 0.8 },
  { path: routes.kontak, priority: 0.82 },
  { path: routes.estimasiBiaya, priority: 0.82 },
  { path: routes.tentangKami, priority: 0.65 },
  { path: routes.artikel, priority: 0.55 },
];
